language: node_js
node_js: stable

cache: yarn

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
  - chmod +x ./.build-client/

install: yarn

script: yarn run build

deploy:
  provider: pages
  skip_cleanup: true
  keep_history: true
  github_token: $GITHUB_TOKEN
  local_dir: ./.build-client/
  target_branch: master
  fqdn: guitarino.github.io
  on:
    branch: development